name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Python, pipenv and Pipfile packages
      uses: palewire/install-python-pipenv-pipfile@v3
      with:
        python-version: 3.9
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint $(git ls-files '*.py')
    - name: Run unit tests
      run: |
        pytest

