name: Pylint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv

      - name: Install dependencies
        run: |
          pipenv install
      - name: Run test suite
        run: |
          pipenv run pytest

      - name: Run linter
        run: |
          pipenv run lint
      - name: Run formatting check
        run: |
          pipenv run format --check